version: '3.3'
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - ./config/db/init.sql:/docker-entrypoint-initdb.d/init.sql
  web:
    build:
      context: .
      dockerfile: ./config/web/Dockerfile
    depends_on:
      - db
    ports:
        - '8080:8080'
    volumes:
        - ./config/web/db.properties:/app/src/main/resources/db.properties
        - ./config/web/mail.properties:/app/src/main/resources/mail.properties
        - ./src:/app/src
  nginx:
    image: nginx:1.17.5-alpine
    ports:
      - 80:80
    volumes:
      - ./config/nginx/http.nginx:/etc/nginx/nginx.conf
      - ./config/nginx/app.nginx:/etc/nginx/conf.d/app.nginx
    depends_on:
      - web
      - db

volumes:
  db:
